// Catalogue de sons pour le mode Montage
// Bibliothèque de 99 sons organisés par catégorie

export type SoundCategory = 'music' | 'ambiance' | 'effect'
export type SoundMood = 'joyeux' | 'triste' | 'suspense' | 'action' | 'magique' | 'nature' | 'effrayant' | 'calme' | 'epique'
export type SoundTheme = 'animaux' | 'nature' | 'ville' | 'superheros' | 'feerique' | 'classique' | 'humain' | 'objets' | 'combat'

export interface Sound {
  id: string
  name: string
  file: string
  category: SoundCategory
  emoji: string
  moods: SoundMood[]
  themes: SoundTheme[]
}

// ============================================================================
// MUSIQUES (13)
// ============================================================================
export const MUSIC_SOUNDS: Sound[] = [
  {
    id: 'ambiance-tranquille',
    name: 'Ambiance Tranquille',
    file: '/sound/music/ambiance-tranquille.mp3',
    category: 'music',
    emoji: '🌿',
    moods: ['calme'],
    themes: ['nature'],
  },
  {
    id: 'aventure-suspense-epique',
    name: 'Aventure Épique',
    file: '/sound/music/aventure-suspense-epique.mp3',
    category: 'music',
    emoji: '⚔️',
    moods: ['suspense', 'action', 'epique'],
    themes: [],
  },
  {
    id: 'cello-suite-bach',
    name: 'Bach - Suite Violoncelle',
    file: '/sound/music/cello-suite-no-1-in-g-major-bwv-1007.mp3',
    category: 'music',
    emoji: '🎻',
    moods: ['calme'],
    themes: ['classique'],
  },
  {
    id: 'chopin-nocturne',
    name: 'Chopin - Nocturne',
    file: '/sound/music/chopin-nocturne-op9-3.mp3',
    category: 'music',
    emoji: '🎹',
    moods: ['calme', 'triste'],
    themes: ['classique'],
  },
  {
    id: 'conte-fee-suspense',
    name: 'Conte de Fées Mystérieux',
    file: '/sound/music/conte-fee-suspense.mp3',
    category: 'music',
    emoji: '🧚',
    moods: ['magique', 'suspense'],
    themes: ['feerique'],
  },
  {
    id: 'feerique',
    name: 'Musique Féerique',
    file: '/sound/music/fe-e-rique.mp3',
    category: 'music',
    emoji: '✨',
    moods: ['magique', 'joyeux'],
    themes: ['feerique'],
  },
  {
    id: 'grave-suspense',
    name: 'Suspense Grave',
    file: '/sound/music/grave-suspense.mp3',
    category: 'music',
    emoji: '😰',
    moods: ['suspense', 'effrayant'],
    themes: [],
  },
  {
    id: 'joyeux',
    name: 'Musique Joyeuse',
    file: '/sound/music/joyeux.mp3',
    category: 'music',
    emoji: '😊',
    moods: ['joyeux'],
    themes: [],
  },
  {
    id: 'tres-joyeux',
    name: 'Très Joyeux',
    file: '/sound/music/tres-joyeux.mp3',
    category: 'music',
    emoji: '🎉',
    moods: ['joyeux'],
    themes: [],
  },
  {
    id: 'vivaldi-spring',
    name: 'Vivaldi - Le Printemps',
    file: '/sound/music/violin-concerto-in-e-major-rv-269-spring-iii-allegro.mp3',
    category: 'music',
    emoji: '🌸',
    moods: ['joyeux', 'calme'],
    themes: ['classique'],
  },
  // Super-héros
  {
    id: 'fight-music',
    name: 'Musique de Combat',
    file: '/sound/music/superheroes/fight-music.mp3',
    category: 'music',
    emoji: '👊',
    moods: ['action', 'epique'],
    themes: ['superheros', 'combat'],
  },
  {
    id: 'super-hero-theme',
    name: 'Thème Super-Héros',
    file: '/sound/music/superheroes/super-hero-theme.mp3',
    category: 'music',
    emoji: '🦸',
    moods: ['epique', 'action'],
    themes: ['superheros'],
  },
  {
    id: 'superhero-suspense',
    name: 'Super-Héros Suspense',
    file: '/sound/music/superheroes/superhero-music-suspens.mp3',
    category: 'music',
    emoji: '🦹',
    moods: ['suspense', 'action'],
    themes: ['superheros'],
  },
]

// ============================================================================
// AMBIANCES (16)
// ============================================================================
export const AMBIANCE_SOUNDS: Sound[] = [
  {
    id: 'ambiance-mystere',
    name: 'Ambiance Mystère',
    file: '/sound/ambiances/ambiance-mystere.mp3',
    category: 'ambiance',
    emoji: '🔮',
    moods: ['suspense', 'magique'],
    themes: [],
  },
  {
    id: 'ambiance-mysterieuse',
    name: 'Ambiance Mystérieuse',
    file: '/sound/ambiances/ambiance-mysterieuse.mp3',
    category: 'ambiance',
    emoji: '🌙',
    moods: ['suspense', 'effrayant'],
    themes: [],
  },
  {
    id: 'ambiance-village',
    name: 'Ambiance Village',
    file: '/sound/ambiances/ambiance-village.mp3',
    category: 'ambiance',
    emoji: '🏘️',
    moods: ['calme'],
    themes: ['ville'],
  },
  {
    id: 'applaudissements',
    name: 'Applaudissements',
    file: '/sound/ambiances/applaudissements-foule.mp3',
    category: 'ambiance',
    emoji: '👏',
    moods: ['joyeux'],
    themes: ['humain'],
  },
  {
    id: 'bruissement-feuilles',
    name: 'Bruissement de Feuilles',
    file: '/sound/ambiances/bruissement-feuilles.mp3',
    category: 'ambiance',
    emoji: '🍃',
    moods: ['calme'],
    themes: ['nature'],
  },
  {
    id: 'bruit-feerique',
    name: 'Bruit Féerique',
    file: '/sound/ambiances/bruit-feerique.mp3',
    category: 'ambiance',
    emoji: '✨',
    moods: ['magique'],
    themes: ['feerique'],
  },
  {
    id: 'eau-qui-coule',
    name: 'Eau qui Coule',
    file: '/sound/ambiances/eau-qui-coule.mp3',
    category: 'ambiance',
    emoji: '💧',
    moods: ['calme'],
    themes: ['nature'],
  },
  {
    id: 'grosse-pluie',
    name: 'Grosse Pluie',
    file: '/sound/ambiances/groose-pluie.mp3',
    category: 'ambiance',
    emoji: '🌧️',
    moods: ['triste', 'calme'],
    themes: ['nature'],
  },
  {
    id: 'mer-tempete',
    name: 'Mer en Tempête',
    file: '/sound/ambiances/mer-tempete.mp3',
    category: 'ambiance',
    emoji: '🌊',
    moods: ['action', 'effrayant'],
    themes: ['nature'],
  },
  {
    id: 'petite-pluie',
    name: 'Petite Pluie',
    file: '/sound/ambiances/petite-pluie.mp3',
    category: 'ambiance',
    emoji: '🌦️',
    moods: ['calme', 'triste'],
    themes: ['nature'],
  },
  {
    id: 'sirene-ville',
    name: 'Sirène de Ville',
    file: '/sound/ambiances/sirene-ville.mp3',
    category: 'ambiance',
    emoji: '🚨',
    moods: ['action', 'suspense'],
    themes: ['ville'],
  },
  {
    id: 'tempete',
    name: 'Tempête',
    file: '/sound/ambiances/tempete.mp3',
    category: 'ambiance',
    emoji: '⛈️',
    moods: ['effrayant', 'action'],
    themes: ['nature'],
  },
  {
    id: 'tonnerre-orage',
    name: 'Tonnerre et Orage',
    file: '/sound/ambiances/tonnerre-orage.mp3',
    category: 'ambiance',
    emoji: '⚡',
    moods: ['effrayant', 'suspense'],
    themes: ['nature'],
  },
  {
    id: 'vent-fort',
    name: 'Vent Fort',
    file: '/sound/ambiances/vent-fort.mp3',
    category: 'ambiance',
    emoji: '💨',
    moods: ['suspense'],
    themes: ['nature'],
  },
  // Super-héros ambiances
  {
    id: 'ambiance-fight',
    name: 'Ambiance Combat',
    file: '/sound/ambiances/superheroes/fight-music.mp3',
    category: 'ambiance',
    emoji: '🥊',
    moods: ['action', 'epique'],
    themes: ['superheros', 'combat'],
  },
  {
    id: 'ambiance-superhero-suspense',
    name: 'Suspense Héroïque',
    file: '/sound/ambiances/superheroes/superhero-music-suspens.mp3',
    category: 'ambiance',
    emoji: '🦸‍♂️',
    moods: ['suspense', 'epique'],
    themes: ['superheros'],
  },
]

// ============================================================================
// EFFETS SONORES (70)
// ============================================================================
export const EFFECT_SOUNDS: Sound[] = [
  // Animaux
  {
    id: 'aboiement-chien',
    name: 'Aboiement de Chien',
    file: '/sound/effects/aboiement-chien.mp3',
    category: 'effect',
    emoji: '🐕',
    moods: [],
    themes: ['animaux'],
  },
  {
    id: 'miaulement-chat',
    name: 'Miaulement de Chat',
    file: '/sound/effects/miaulement-chat.mp3',
    category: 'effect',
    emoji: '🐱',
    moods: [],
    themes: ['animaux'],
  },
  {
    id: 'vache-meugle',
    name: 'Vache qui Meugle',
    file: '/sound/effects/vaches-meugle.mp3',
    category: 'effect',
    emoji: '🐄',
    moods: [],
    themes: ['animaux'],
  },
  {
    id: 'gallop-cheval',
    name: 'Galop de Cheval',
    file: '/sound/effects/gallop-cheval.mp3',
    category: 'effect',
    emoji: '🐴',
    moods: ['action'],
    themes: ['animaux'],
  },
  {
    id: 'grognement-loup',
    name: 'Grognement de Loup',
    file: '/sound/effects/grognement-loup.mp3',
    category: 'effect',
    emoji: '🐺',
    moods: ['effrayant'],
    themes: ['animaux'],
  },
  {
    id: 'rugissement-lion',
    name: 'Rugissement de Lion',
    file: '/sound/effects/rugissement-lyon.mp3',
    category: 'effect',
    emoji: '🦁',
    moods: ['effrayant', 'epique'],
    themes: ['animaux'],
  },
  {
    id: 'cri-elephant',
    name: 'Cri d\'Éléphant',
    file: '/sound/effects/cri-elephant.mp3',
    category: 'effect',
    emoji: '🐘',
    moods: [],
    themes: ['animaux'],
  },
  {
    id: 'grenouille-croasse',
    name: 'Grenouille qui Croasse',
    file: '/sound/effects/grenouille-croasse.mp3',
    category: 'effect',
    emoji: '🐸',
    moods: [],
    themes: ['animaux', 'nature'],
  },
  {
    id: 'cri-baleines',
    name: 'Chant des Baleines',
    file: '/sound/effects/cri-baleines.mp3',
    category: 'effect',
    emoji: '🐋',
    moods: ['calme', 'magique'],
    themes: ['animaux'],
  },
  // Oiseaux
  {
    id: 'cri-chouette',
    name: 'Cri de Chouette',
    file: '/sound/effects/cri-de-chouette.mp3',
    category: 'effect',
    emoji: '🦉',
    moods: ['effrayant'],
    themes: ['animaux', 'nature'],
  },
  {
    id: 'cri-chouette-2',
    name: 'Hulument de Chouette',
    file: '/sound/effects/cri-2-chouette.mp3',
    category: 'effect',
    emoji: '🦉',
    moods: ['suspense'],
    themes: ['animaux', 'nature'],
  },
  {
    id: 'cri-aigle',
    name: 'Cri d\'Aigle',
    file: '/sound/effects/cri-aigle.mp3',
    category: 'effect',
    emoji: '🦅',
    moods: ['epique'],
    themes: ['animaux'],
  },
  {
    id: 'cri-coq',
    name: 'Cocorico',
    file: '/sound/effects/cri-coq.mp3',
    category: 'effect',
    emoji: '🐓',
    moods: ['joyeux'],
    themes: ['animaux'],
  },
  {
    id: 'cris-mouettes',
    name: 'Cris de Mouettes',
    file: '/sound/effects/cris-mouettes.mp3',
    category: 'effect',
    emoji: '🕊️',
    moods: ['calme'],
    themes: ['animaux', 'nature'],
  },
  // Dinosaures
  {
    id: 'cri-raptor',
    name: 'Cri de Raptor',
    file: '/sound/effects/cri-raptor.mp3',
    category: 'effect',
    emoji: '🦖',
    moods: ['effrayant', 'action'],
    themes: ['animaux'],
  },
  {
    id: 'cri-raptor-2',
    name: 'Rugissement Raptor',
    file: '/sound/effects/cri-2-raptor.mp3',
    category: 'effect',
    emoji: '🦕',
    moods: ['effrayant'],
    themes: ['animaux'],
  },
  {
    id: 'petit-dinosaure',
    name: 'Petit Dinosaure',
    file: '/sound/effects/bruit-petit-dinosaure.mp3',
    category: 'effect',
    emoji: '🦎',
    moods: [],
    themes: ['animaux'],
  },
  {
    id: 'oiseau-prehistorique',
    name: 'Oiseau Préhistorique',
    file: '/sound/effects/oiseau-prehistorique.mp3',
    category: 'effect',
    emoji: '🦤',
    moods: ['effrayant'],
    themes: ['animaux'],
  },
  // Humains
  {
    id: 'enfant-rit',
    name: 'Rire d\'Enfant',
    file: '/sound/effects/enfant-rit.mp3',
    category: 'effect',
    emoji: '👶',
    moods: ['joyeux'],
    themes: ['humain'],
  },
  {
    id: 'rire-femme',
    name: 'Rire de Femme',
    file: '/sound/effects/rire-femme.mp3',
    category: 'effect',
    emoji: '😂',
    moods: ['joyeux'],
    themes: ['humain'],
  },
  {
    id: 'homme-pleure',
    name: 'Homme qui Pleure',
    file: '/sound/effects/homme-pleure.mp3',
    category: 'effect',
    emoji: '😢',
    moods: ['triste'],
    themes: ['humain'],
  },
  {
    id: 'cri-surprise',
    name: 'Cri de Surprise',
    file: '/sound/effects/cri-suprise.mp3',
    category: 'effect',
    emoji: '😱',
    moods: ['suspense'],
    themes: ['humain'],
  },
  {
    id: 'homme-cours',
    name: 'Pas de Course',
    file: '/sound/effects/homme-cours.mp3',
    category: 'effect',
    emoji: '🏃',
    moods: ['action'],
    themes: ['humain'],
  },
  {
    id: 'pas-dehors',
    name: 'Pas Dehors',
    file: '/sound/effects/pas-dehors.mp3',
    category: 'effect',
    emoji: '👣',
    moods: [],
    themes: ['humain'],
  },
  {
    id: 'pas-neige',
    name: 'Pas dans la Neige',
    file: '/sound/effects/pas-neige.mp3',
    category: 'effect',
    emoji: '❄️',
    moods: ['calme'],
    themes: ['humain', 'nature'],
  },
  {
    id: 'pas-geant',
    name: 'Pas de Géant',
    file: '/sound/effects/bruits-de-pas-geant.mp3',
    category: 'effect',
    emoji: '👹',
    moods: ['effrayant', 'suspense'],
    themes: ['humain'],
  },
  // Action & Combat
  {
    id: 'explosion',
    name: 'Explosion',
    file: '/sound/effects/explosion.mp3',
    category: 'effect',
    emoji: '💥',
    moods: ['action'],
    themes: ['combat'],
  },
  {
    id: 'coup-de-poing',
    name: 'Coup de Poing',
    file: '/sound/effects/coup-de-poing.mp3',
    category: 'effect',
    emoji: '👊',
    moods: ['action'],
    themes: ['combat'],
  },
  {
    id: 'cout-hache',
    name: 'Coup de Hache',
    file: '/sound/effects/cout-hache.mp3',
    category: 'effect',
    emoji: '🪓',
    moods: ['action'],
    themes: ['combat'],
  },
  {
    id: 'cout-hache-2',
    name: 'Hache qui Frappe',
    file: '/sound/effects/cout-hache-2.mp3',
    category: 'effect',
    emoji: '🪓',
    moods: ['action'],
    themes: ['combat'],
  },
  // Objets & Maison
  {
    id: 'porte-grince',
    name: 'Porte qui Grince',
    file: '/sound/effects/porte-grince.mp3',
    category: 'effect',
    emoji: '🚪',
    moods: ['effrayant', 'suspense'],
    themes: ['objets'],
  },
  {
    id: 'chute-objet-metallique',
    name: 'Chute d\'Objet Métallique',
    file: '/sound/effects/chute-objet-metallique.mp3',
    category: 'effect',
    emoji: '🔧',
    moods: [],
    themes: ['objets'],
  },
  {
    id: 'papier-froisse',
    name: 'Papier Froissé',
    file: '/sound/effects/papier-froisse.mp3',
    category: 'effect',
    emoji: '📄',
    moods: [],
    themes: ['objets'],
  },
  {
    id: 'bruit-marteau',
    name: 'Coup de Marteau',
    file: '/sound/effects/bruit-marteau.mp3',
    category: 'effect',
    emoji: '🔨',
    moods: [],
    themes: ['objets'],
  },
  {
    id: 'bruit-outils',
    name: 'Bruits d\'Outils',
    file: '/sound/effects/bruit-outils.mp3',
    category: 'effect',
    emoji: '🛠️',
    moods: [],
    themes: ['objets'],
  },
  {
    id: 'bruit-ordinateur',
    name: 'Ordinateur',
    file: '/sound/effects/bruit-ordinateur.mp3',
    category: 'effect',
    emoji: '💻',
    moods: [],
    themes: ['objets'],
  },
  // Science-fiction
  {
    id: 'teleportation',
    name: 'Téléportation',
    file: '/sound/effects/teleportation.mp3',
    category: 'effect',
    emoji: '🌀',
    moods: ['magique'],
    themes: ['feerique'],
  },
  {
    id: 'courant-electrique',
    name: 'Courant Électrique',
    file: '/sound/effects/courant-electric.mp3',
    category: 'effect',
    emoji: '⚡',
    moods: ['action'],
    themes: [],
  },
  {
    id: 'porte-spatiale',
    name: 'Porte Spatiale',
    file: '/sound/effects/ouverture-porte-spatial.mp3',
    category: 'effect',
    emoji: '🚀',
    moods: ['magique'],
    themes: [],
  },
  // Effets Super-héros
  {
    id: 'sh-applause',
    name: 'Applaudissements',
    file: '/sound/effects/superheroes/applause.mp3',
    category: 'effect',
    emoji: '👏',
    moods: ['joyeux'],
    themes: ['superheros'],
  },
  {
    id: 'sh-bell-ring',
    name: 'Cloche',
    file: '/sound/effects/superheroes/bell-ring.mp3',
    category: 'effect',
    emoji: '🔔',
    moods: [],
    themes: ['superheros'],
  },
  {
    id: 'sh-radar',
    name: 'Bruit de Radar',
    file: '/sound/effects/superheroes/bruit-radar.mp3',
    category: 'effect',
    emoji: '📡',
    moods: ['suspense'],
    themes: ['superheros'],
  },
  {
    id: 'sh-cape-swoosh',
    name: 'Cape qui Vole',
    file: '/sound/effects/superheroes/cape-swoosh.mp3',
    category: 'effect',
    emoji: '🦸',
    moods: ['action'],
    themes: ['superheros'],
  },
  {
    id: 'sh-chain-clink',
    name: 'Chaînes',
    file: '/sound/effects/superheroes/chain-clink.mp3',
    category: 'effect',
    emoji: '⛓️',
    moods: [],
    themes: ['superheros'],
  },
  {
    id: 'sh-crowd-cheer',
    name: 'Foule qui Acclame',
    file: '/sound/effects/superheroes/crowd-cheer.mp3',
    category: 'effect',
    emoji: '🎉',
    moods: ['joyeux', 'epique'],
    themes: ['superheros'],
  },
  {
    id: 'sh-electric-shock',
    name: 'Choc Électrique',
    file: '/sound/effects/superheroes/electric-shock.mp3',
    category: 'effect',
    emoji: '⚡',
    moods: ['action'],
    themes: ['superheros'],
  },
  {
    id: 'sh-energy-hum',
    name: 'Énergie Vibrante',
    file: '/sound/effects/superheroes/energy-hum.mp3',
    category: 'effect',
    emoji: '✨',
    moods: ['magique'],
    themes: ['superheros'],
  },
  {
    id: 'sh-explosion',
    name: 'Explosion Héroïque',
    file: '/sound/effects/superheroes/explosion.mp3',
    category: 'effect',
    emoji: '💥',
    moods: ['action', 'epique'],
    themes: ['superheros', 'combat'],
  },
  {
    id: 'sh-metal-clash',
    name: 'Choc Métallique',
    file: '/sound/effects/superheroes/fifght-metal-clash.mp3',
    category: 'effect',
    emoji: '⚔️',
    moods: ['action'],
    themes: ['superheros', 'combat'],
  },
  {
    id: 'sh-glass-shatter',
    name: 'Verre Brisé',
    file: '/sound/effects/superheroes/glass-shatter.mp3',
    category: 'effect',
    emoji: '💔',
    moods: ['action'],
    themes: ['superheros'],
  },
  {
    id: 'sh-heartbeat',
    name: 'Battement de Cœur',
    file: '/sound/effects/superheroes/heartbeat.mp3',
    category: 'effect',
    emoji: '💓',
    moods: ['suspense'],
    themes: ['superheros'],
  },
  {
    id: 'sh-heavy-landing',
    name: 'Atterrissage Lourd',
    file: '/sound/effects/superheroes/heavy-landing.mp3',
    category: 'effect',
    emoji: '💪',
    moods: ['action', 'epique'],
    themes: ['superheros'],
  },
  {
    id: 'sh-hero-shout',
    name: 'Cri Héroïque',
    file: '/sound/effects/superheroes/hero-shout.mp3',
    category: 'effect',
    emoji: '🦸‍♂️',
    moods: ['epique', 'action'],
    themes: ['superheros'],
  },
  {
    id: 'sh-hero-shout-2',
    name: 'Cri de Victoire',
    file: '/sound/effects/superheroes/hero-shout2.mp3',
    category: 'effect',
    emoji: '🏆',
    moods: ['joyeux', 'epique'],
    themes: ['superheros'],
  },
  {
    id: 'sh-jet-flight',
    name: 'Vol de Jet',
    file: '/sound/effects/superheroes/jet-flight.mp3',
    category: 'effect',
    emoji: '✈️',
    moods: ['action'],
    themes: ['superheros'],
  },
  {
    id: 'sh-laser-shot',
    name: 'Tir Laser',
    file: '/sound/effects/superheroes/laser-shot.mp3',
    category: 'effect',
    emoji: '🔫',
    moods: ['action'],
    themes: ['superheros', 'combat'],
  },
  {
    id: 'sh-tir-laser',
    name: 'Rayon Laser',
    file: '/sound/effects/superheroes/tir-laser.mp3',
    category: 'effect',
    emoji: '💫',
    moods: ['action'],
    themes: ['superheros', 'combat'],
  },
  {
    id: 'sh-metal-clash-2',
    name: 'Combat Métal',
    file: '/sound/effects/superheroes/metal-clash.mp3',
    category: 'effect',
    emoji: '🗡️',
    moods: ['action'],
    themes: ['superheros', 'combat'],
  },
  {
    id: 'sh-power-rumble',
    name: 'Grondement de Pouvoir',
    file: '/sound/effects/superheroes/power-rumble.mp3',
    category: 'effect',
    emoji: '🌋',
    moods: ['epique'],
    themes: ['superheros'],
  },
  {
    id: 'sh-powerful-jump',
    name: 'Super Saut',
    file: '/sound/effects/superheroes/powerful-jump.mp3',
    category: 'effect',
    emoji: '🦘',
    moods: ['action'],
    themes: ['superheros'],
  },
  {
    id: 'sh-projectile-whistle',
    name: 'Projectile Sifflant',
    file: '/sound/effects/superheroes/projectile-whistle.mp3',
    category: 'effect',
    emoji: '🎯',
    moods: ['action'],
    themes: ['superheros', 'combat'],
  },
  {
    id: 'sh-punch',
    name: 'Super Punch',
    file: '/sound/effects/superheroes/punch.mp3',
    category: 'effect',
    emoji: '💥',
    moods: ['action'],
    themes: ['superheros', 'combat'],
  },
  {
    id: 'sh-running-steps',
    name: 'Course Héroïque',
    file: '/sound/effects/superheroes/running-steps.mp3',
    category: 'effect',
    emoji: '🏃‍♂️',
    moods: ['action'],
    themes: ['superheros'],
  },
  {
    id: 'sh-shield-clash',
    name: 'Bouclier',
    file: '/sound/effects/superheroes/shield-clash.mp3',
    category: 'effect',
    emoji: '🛡️',
    moods: ['action'],
    themes: ['superheros', 'combat'],
  },
  {
    id: 'sh-speed-whistle',
    name: 'Vitesse Supersonique',
    file: '/sound/effects/superheroes/speed-whistle.mp3',
    category: 'effect',
    emoji: '💨',
    moods: ['action'],
    themes: ['superheros'],
  },
  {
    id: 'sh-teleport-woosh',
    name: 'Téléportation',
    file: '/sound/effects/superheroes/teleport-woosh.mp3',
    category: 'effect',
    emoji: '🌀',
    moods: ['magique'],
    themes: ['superheros'],
  },
  {
    id: 'sh-thunder-rumble',
    name: 'Tonnerre Héroïque',
    file: '/sound/effects/superheroes/thunder-rumble.mp3',
    category: 'effect',
    emoji: '⛈️',
    moods: ['epique'],
    themes: ['superheros'],
  },
  {
    id: 'sh-victory-shout',
    name: 'Cri de Victoire',
    file: '/sound/effects/superheroes/victory-shout.mp3',
    category: 'effect',
    emoji: '🎊',
    moods: ['joyeux', 'epique'],
    themes: ['superheros'],
  },
  {
    id: 'sh-vol-supersonique',
    name: 'Vol Supersonique',
    file: '/sound/effects/superheroes/vol-supersonique.mp3',
    category: 'effect',
    emoji: '🚀',
    moods: ['action', 'epique'],
    themes: ['superheros'],
  },
  {
    id: 'sh-wind-howl',
    name: 'Vent Hurlant',
    file: '/sound/effects/superheroes/wind-howl.mp3',
    category: 'effect',
    emoji: '🌪️',
    moods: ['suspense'],
    themes: ['superheros', 'nature'],
  },
]

// ============================================================================
// CATALOGUE COMPLET
// ============================================================================
export const ALL_SOUNDS: Sound[] = [
  ...MUSIC_SOUNDS,
  ...AMBIANCE_SOUNDS,
  ...EFFECT_SOUNDS,
]

// Helpers pour filtrer
export function getSoundsByCategory(category: SoundCategory): Sound[] {
  return ALL_SOUNDS.filter(s => s.category === category)
}

export function getSoundsByMood(mood: SoundMood): Sound[] {
  return ALL_SOUNDS.filter(s => s.moods.includes(mood))
}

export function getSoundsByTheme(theme: SoundTheme): Sound[] {
  return ALL_SOUNDS.filter(s => s.themes.includes(theme))
}

export function searchSounds(query: string): Sound[] {
  const q = query.toLowerCase()
  return ALL_SOUNDS.filter(s => 
    s.name.toLowerCase().includes(q) ||
    s.moods.some(m => m.includes(q)) ||
    s.themes.some(t => t.includes(q))
  )
}

// Labels pour l'UI
export const MOOD_LABELS: Record<SoundMood, { label: string; emoji: string }> = {
  joyeux: { label: 'Joyeux', emoji: '😊' },
  triste: { label: 'Triste', emoji: '😢' },
  suspense: { label: 'Suspense', emoji: '😰' },
  action: { label: 'Action', emoji: '💥' },
  magique: { label: 'Magique', emoji: '✨' },
  nature: { label: 'Nature', emoji: '🌿' },
  effrayant: { label: 'Effrayant', emoji: '👻' },
  calme: { label: 'Calme', emoji: '😌' },
  epique: { label: 'Épique', emoji: '⚔️' },
}

export const THEME_LABELS: Record<SoundTheme, { label: string; emoji: string }> = {
  animaux: { label: 'Animaux', emoji: '🐾' },
  nature: { label: 'Nature', emoji: '🌳' },
  ville: { label: 'Ville', emoji: '🏙️' },
  superheros: { label: 'Super-Héros', emoji: '🦸' },
  feerique: { label: 'Féerique', emoji: '🧚' },
  classique: { label: 'Classique', emoji: '🎼' },
  humain: { label: 'Humain', emoji: '👤' },
  objets: { label: 'Objets', emoji: '🔧' },
  combat: { label: 'Combat', emoji: '⚔️' },
}

export const CATEGORY_LABELS: Record<SoundCategory, { label: string; emoji: string }> = {
  music: { label: 'Musiques', emoji: '🎵' },
  ambiance: { label: 'Ambiances', emoji: '🌧️' },
  effect: { label: 'Effets', emoji: '💥' },
}
